---
title: "TT - Economist movies"
output: 
  html_document: 
    keep_md: yes
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
library(tidytext)
library(lubridate)
library(scales)

theme_set(theme_minimal())
```

Load raw CSV data and view
```{r}
raw_movie_data <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-01-08/IMDb_Economist_tv_ratings.csv")
```

Clean up data: splitting genre column, removing title id and parsing date
```{r}
movie_data_clean <- raw_movie_data %>%
  select(-titleId) %>%
  rename(Season = seasonNumber) %>%
  separate(genres, into = c("G1", "G2", "G3"), sep = ",") %>%
  mutate(date = ymd(date),
         G3 = replace_na(G3, "")) %>%
  gather(key = Genre_num, value = Genre, c("G1", "G2", "G3")) %>%
  arrange(title, Genre) %>%
  filter(Genre != "") %>%
  select(-Genre_num)
```

How many types of each genre are there?
```{r}
genre_count <- movie_data_clean %>%
  distinct(title, .keep_all = T) %>%  
  count(Genre) %>%
  ggplot(aes(reorder(Genre,-n), n, fill = Genre)) +
  geom_col(show.legend = F) +
  labs(y = "Frequency") +
  scale_y_continuous(labels = comma_format())

genre_count
```


Which genres had the most amount of seasons?
```{r}
season_by_genre <- movie_data_clean %>%
  group_by(title) %>%
  mutate(max_season = max(Season)) %>%
  distinct(title, .keep_all = T) %>%
  ungroup() %>%
  group_by(Genre) %>%
  summarise(Av_seasons = mean(max_season),
            SE = sd(max_season/sqrt(length(max_season)))) %>%
  mutate(ymin = Av_seasons - SE,
         ymax = Av_seasons + SE) %>%
  ggplot(aes(x = reorder(Genre,-Av_seasons), y = Av_seasons, fill = Genre)) +
  geom_col(show.legend = F) +
  geom_errorbar(aes(ymin = ymin, ymax = ymax), width = 0.2) +
  labs(y = "Average number of seasons",
       caption = "error bars highlight SEM",
       x = "Genre")

season_by_genre
  
```

How do the ratings and viewership of genres change across seasons? 
limited to 10 seasons
```{r}
seasonal_changes <- movie_data_clean %>%
  distinct(Season, title, .keep_all = T) %>%
  filter(Season < 21) %>%
  group_by(Genre, Season) %>%
  summarise(avg_rating = mean(av_rating),
            avg_share = mean(share),
            rating_SE = sd(av_rating)/sqrt(length(av_rating)),
            share_SE = sd(share)/sqrt(length(share)),
            shows = n()) %>%
  mutate(ymin_rat = avg_rating - rating_SE,
         ymax_rat = avg_rating + rating_SE,
         ymin_share = avg_share- share_SE,
         ymax_share = avg_share + share_SE) %>%
  select(-rating_SE, -share_SE)

seasonal_ratings <- seasonal_changes %>%
  ggplot(aes(Season, avg_rating, col = Genre)) +
  geom_line() +
  geom_point() +
  labs(y = "Average rating per season") +
  scale_color_viridis_d() +
  scale_y_continuous(limits = c(0,10))

seasonal_ratings

seasonal_share <- seasonal_changes %>%
  ggplot(aes(Season, avg_share, col = Genre)) +
  geom_line() +
  geom_point() +
  labs(y = "Average audience share per season") +
  scale_color_viridis_d() +
  scale_y_continuous(limits = c(0,6))

seasonal_share

```


is there a correlation between date, genre and rating / viewership?
```{r}
date_impacted_figures <- movie_data_clean %>%
  distinct(title, .keep_all = T) %>%
  mutate(Month = month(date, label = T),
         Year = year(date)) %>%
  group_by(Year, Month, Genre) %>%
  summarise(avg_rating = mean(av_rating),
            avg_share = mean(share))


genre_years <- date_impacted_figures %>%
  group_by(Year, Genre) %>%
  summarise(avg_rating = mean(avg_rating),
            avg_share = mean(avg_share)) %>%
  gather(Measure, Score, avg_rating, avg_share) %>%
  ggplot(aes(x = Year, y = Score, col = Measure, group = Measure)) +
  geom_line() +
  geom_point() +
  facet_wrap(~Genre)

genre_years


genre_months <- date_impacted_figures %>%
  group_by(Month, Genre) %>%
  summarise(avg_rating = mean(avg_rating),
            avg_share = mean(avg_share)) %>%
  gather(Measure, Score, avg_rating, avg_share) %>%
  ggplot(aes(x = Month, y = Score, col = Measure, group = Measure)) +
  geom_line() +
  geom_point() +
  facet_wrap(~Genre)

genre_months
  
```

